# Configuration for website and doc generation on RTD
version: 2

sphinx:
  configuration: docs/source/conf.py

build:
  os: ubuntu-lts-latest
  tools:
    python: "3.14"

python:
  install:
    - method: pip
      path: .
