# Configuration for website and doc generation on RTD
version: 2

sphinx:
  configuration: docs/source/conf.py

build:
  os: ubuntu-22.04
  tools:
    python: "mambaforge-22.9"

conda:
  environment: environment.yml

python:
  install:
    - method: setuptools
      path: .
