from __future__ import annotations
from typing import Optional

import numpy as np
import torch

from qimpy import TreeNode, rc, log
from qimpy.rc import MPI
from qimpy.io import CheckpointPath, CheckpointContext
from qimpy.mpi import ProcessGrid, BufferView
from ..material import Material
from . import TensorList, Geometry
from ._dg2d import vandermonde2d
from ._dg_mesh import load_mesh
from ._dg_mpi import (compute_partition, SpatialPartition, DistributedAdvect,
                      mpi_halo_exchange)


class TriSet(Geometry):
    """Discontinuous-Galerkin geometry on an externally supplied triangle mesh,
    parallel over both momentum and space.

    The triangle mesh is produced by external tooling (see _dg_mesh.load_mesh)
    and supplied via ``mesh_file``; qimpy does not triangulate. The mesh is then
    decomposed across the process grid's real-space ("r") communicator: each
    rank owns a subset of elements plus a one-element ghost ring, runs the DG
    operators on that local submesh, and exchanges ghost state each RHS so that
    faces crossing a rank boundary read the correct neighbor trace. This is
    orthogonal to the material's momentum ("k") parallelization, so a run with
    process grid (Pr, Pk) parallelizes over both. Physical boundary faces are
    classified by the mesh's marker names; for checkpoint/plot output the DG
    field is sampled onto a mesh-derived bounding-box grid, reduced across the
    r-communicator so each rank contributes its owned region.
    """

    dg: object
    order: int

    def __init__(
        self,
        *,
        material: Material,
        mesh_file: str,
        contacts: dict[str, Optional[dict]],
        order: int = 3,
        render_grid_spacing: Optional[float] = None,
        save_rho: bool = False,
        process_grid: ProcessGrid,
        checkpoint_in: CheckpointPath = CheckpointPath(),
    ):
        """
        Parameters
        ----------
        mesh_file
            :yaml:`Path to an external triangle mesh (.npz) to solve on.`
            Generated by any external mesher; qimpy does not triangulate.
        contacts
            :yaml:`Dictionary of contact names to parameters.`
            Names must match boundary markers in the mesh file.
        order
            :yaml:`Polynomial order N of the DG basis on each triangle.`
        render_grid_spacing
            :yaml:`Structured-grid spacing used only for checkpoint/plot output.`
        save_rho
            :yaml:`Whether to write the full density matrix at each checkpoint.`
        """
        TreeNode.__init__(self)
        self.material = material
        self.comm = process_grid.get_comm("r")        # spatial communicator
        self.order = order
        self.mesh_file = mesh_file
        self.save_rho = save_rho
        self.contacts = contacts

        # --- external mesh (global, on every rank), then spatial decomposition ---
        mesh = load_mesh(mesh_file)
        self.mesh = mesh
        nparts = self.comm.size
        self._distributed = nparts > 1
        K = len(mesh.EToV)
        part = np.empty(K, np.int32)
        if self.comm.rank == 0:
            part[:] = compute_partition(mesh, nparts)
        self.comm.Bcast(part, root=0)
        self.part = SpatialPartition(mesh, order, part, self.comm.rank)
        # periodic linking only without spatial decomposition (periodic partners
        # may otherwise straddle ranks); external straight meshes are the norm
        if getattr(mesh, "_lattice", None) and not self._distributed:
            self.part.dg.make_periodic(mesh._lattice)
        elif getattr(mesh, "_lattice", None) and self._distributed:
            log.info("tri_set: periodic lattice ignored under spatial "
                     "decomposition (Pr>1); run periodic cases with Pr=1.")
        self.dist = DistributedAdvect(self.part, material, contacts)
        self.dg = self.part.dg
        self.adv = self.dist.adv
        self._vx, self._vy = self.dist.vx, self.dist.vy
        self.Nk = self.dist.Nk

        # global max stable time step (min over all spatial ranks)
        v = material.transport_velocity.detach().cpu().numpy()
        dt_local = float(0.4 * self.dg.dt_scale
                         / max(np.hypot(v[:, 0], v[:, 1]).max(), 1e-300))
        self.dt_max = self.comm.allreduce(dt_local, op=MPI.MIN)
        if self._distributed:
            log.info(f"tri_set: spatial decomposition over {nparts} ranks "
                     f"(this rank: {self.part.n_owned} owned + "
                     f"{self.dg.K - self.part.n_owned} ghost elements)")

        # --- render grid (global bbox) + per-rank interpolation onto owned region
        self._build_render_grid(render_grid_spacing)
        self._interp = [self._build_interp(q) for q in self._render_q]
        self._stash_t: list[float] = []
        self._stash_i: list[int] = []
        self._stash_obs: list[list[np.ndarray]] = [[] for _ in self._render_q]

        # --- initial density: material equilibrium tiled onto local DG nodes ---
        dtype = material.transport_velocity.dtype
        Nkbb = material.rho0.numel()
        rho0_nodal = material.rho0.flatten().to(rc.device).reshape(1, 1, Nkbb) \
            * torch.ones(self.dg.Np, self.dg.K, Nkbb, device=rc.device, dtype=dtype)
        self._rho = self.adv.apply_mass(rho0_nodal)

    # ------------------------------------------------------------------ #
    def _build_render_grid(self, render_grid_spacing):
        """Structured bounding-box grid over the GLOBAL mesh (identical on every
        rank), for checkpoint/plot output (single 'quad')."""
        gx, gy = self.mesh.VX, self.mesh.VY
        xmin, xmax = float(gx.min()), float(gx.max())
        ymin, ymax = float(gy.min()), float(gy.max())
        span = max(xmax - xmin, ymax - ymin)
        gs = render_grid_spacing if render_grid_spacing else span / 150.0
        nx = max(2, int(np.ceil((xmax - xmin) / gs)))
        ny = max(2, int(np.ceil((ymax - ymin) / gs)))
        dx = (xmax - xmin) / nx; dy = (ymax - ymin) / ny
        xg = xmin + (np.arange(nx) + 0.5) * dx
        yg = ymin + (np.arange(ny) + 0.5) * dy
        X, Y = np.meshgrid(xg, yg, indexing="ij")
        self._render_q = [torch.from_numpy(np.stack([X, Y], -1)).to(rc.device)]
        self._render_g = [torch.full((nx, ny), dx * dy, device=rc.device,
                                     dtype=torch.float64)]
        self._render_size = [(nx, ny)]
        self._bbox = (xmin, xmax, ymin, ymax)
        self._grid_spacing = max(dx, dy)
        # mask of render points inside the true (global) domain, so output cells
        # outside the device read NaN regardless of how space is partitioned
        import matplotlib.tri as mtri
        finder = mtri.Triangulation(self.mesh.VX, self.mesh.VY,
                                    self.mesh.EToV).get_trifinder()
        self._inside_global = [finder(X.ravel(), Y.ravel()).reshape(nx, ny) >= 0]

    def _build_interp(self, q_grid):
        """Locate each render point in an OWNED element and build DG nodal-interp
        weights; flag points outside this rank's owned region so they can be
        masked (and, under decomposition, summed across ranks)."""
        dg = self.dg
        n_owned = self.part.n_owned
        q = q_grid.detach().cpu().numpy().reshape(-1, 2)
        A = np.stack([dg.VX[dg.EToV[:, 0]], dg.VY[dg.EToV[:, 0]]], axis=1)
        B = np.stack([dg.VX[dg.EToV[:, 1]], dg.VY[dg.EToV[:, 1]]], axis=1)
        C = np.stack([dg.VX[dg.EToV[:, 2]], dg.VY[dg.EToV[:, 2]]], axis=1)
        Minv = np.linalg.inv(np.stack([B - A, C - A], axis=-1))
        VinvT = np.linalg.inv(dg.V).T
        tri = np.empty(len(q), int); W = np.empty((len(q), dg.Np))
        inside = np.empty(len(q), bool)
        for p in range(len(q)):
            bc = np.einsum('kij,kj->ki', Minv, q[p][None, :] - A)
            b1 = 1.0 - bc.sum(1)
            score = np.minimum.reduce([b1, bc[:, 0], bc[:, 1]])
            score[n_owned:] = -np.inf                # only place points in owned elems
            k = int(np.argmax(score))
            inside[p] = score[k] >= -1e-9
            b = np.array([bc[k, 0], bc[k, 1], 1.0 - bc[k].sum()])
            if score[k] < 0.0:
                b = np.clip(b, 0.0, None); b = b / b.sum()
            vrow = vandermonde2d(dg.N, np.array([2 * b[0] - 1]),
                                 np.array([2 * b[1] - 1]))[0]
            tri[p] = k; W[p] = VinvT @ vrow
        return tri, W, inside

    def _sample_grid(self, i_quad):
        rho = self.density.detach().cpu().numpy()    # density u = M^-1 w
        tri, W, inside = self._interp[i_quad]
        grid = np.einsum('pi,ipk->pk', W, rho[:, tri, :])
        # outside this rank's owned region -> 0 so the cross-rank sum picks up
        # each point from its single owner; true-domain NaN mask applied in stash
        grid[~inside] = 0.0
        return torch.from_numpy(
            grid.reshape(*self._render_size[i_quad], -1)).to(self._rho)

    # ---- qimpy Geometry contract ----
    @property
    def rho(self) -> TensorList:
        return TensorList([self._rho])

    @rho.setter
    def rho(self, rho_new: TensorList) -> None:
        self._rho = rho_new[0]

    @property
    def density(self) -> torch.Tensor:
        """Nodal density u = M_k^{-1} w recovered from the conservative state."""
        return self.adv.apply_mass_inv(self._rho)

    @density.setter
    def density(self, dens: torch.Tensor) -> None:
        self._rho = self.adv.apply_mass(dens.to(self._rho))

    def rho_dot(self, rho: TensorList, t: float) -> TensorList:
        w = rho[0]
        if self._distributed:
            mpi_halo_exchange(self.comm, self.part, w)   # refresh ghost rows
        # Advection of the conservative variable (per channel; no k-comm).
        spatial = self.adv.rhs_w(w, self._vx, self._vy, t)
        # Collisions act on the density; map dn/dt back to w-space via M.
        u = self.adv.apply_mass_inv(w)
        coll_u = self.material.rho_dot(
            u.reshape(-1, 1, self.Nk), t, id(self)).reshape(u.shape)
        coll = self.adv.apply_mass(coll_u)
        return TensorList([spatial + coll])

    def update_stash(self, i_step: int, t: float) -> None:
        self._stash_i.append(i_step); self._stash_t.append(t)
        for i_quad in range(len(self._render_q)):
            obs = self.material.measure_observables(self._sample_grid(i_quad), t)
            obs_np = np.ascontiguousarray(obs.detach().cpu().numpy())
            if self._distributed:                        # combine owned regions
                self.comm.Allreduce(MPI.IN_PLACE, BufferView(obs_np))
            obs_np[~self._inside_global[i_quad]] = np.nan  # blank outside device
            self._stash_obs[i_quad].append(obs_np)

    def _save_checkpoint(
        self, cp_path: CheckpointPath, context: CheckpointContext
    ) -> list[str]:
        attrs = cp_path.attrs
        attrs["mesh_file"] = self.mesh_file
        attrs["geometry_type"] = "tri_set"
        attrs["dg_order"] = self.order
        attrs["grid_spacing"] = self._grid_spacing
        xmin, xmax, ymin, ymax = self._bbox
        quads = np.array([[[xmin, ymin], [xmax, ymin], [xmax, ymax], [xmin, ymax]]])
        verts = quads.reshape(-1, 2)
        # write() / write_str() are collective-create + head-write (all ranks call)
        saved = [
            cp_path.write("vertices", torch.from_numpy(verts)),
            cp_path.write("quads", torch.from_numpy(quads)),
            cp_path.write("displacements", torch.from_numpy(np.zeros((1, 4, 2)))),
            cp_path.write("adjacency", torch.from_numpy(-np.ones((1, 4), int))),
            cp_path.write("grid_size",
                          torch.from_numpy(np.array([self._render_size[0]], int))),
            cp_path.write("contacts", torch.from_numpy(np.zeros((0, 3)))),
            cp_path.write("apertures", torch.from_numpy(np.zeros((0, 3)))),
            "q", "g", "observables",
        ]
        cp_path.write_str("contact_names", ",".join(self.contacts.keys()))
        cp_path.write_str("aperture_names", "")
        cp_path.write_str("observable_names",
                          ",".join(self.material.get_observable_names()))
        cp_path["t"] = np.array(self._stash_t)
        cp_path["i_step"] = np.array(self._stash_i)
        n_obs = len(self.material.get_observable_names())
        n_stash = len(self._stash_t)
        checkpoint, path = cp_path
        for i_quad in range(len(self._render_size)):
            cp_q = CheckpointPath(checkpoint, f"{path}/quad{i_quad}")
            N = self._render_size[i_quad]
            cp_q.create_dataset("q", tuple(N) + (2,), np.float64)        # collective
            cp_q.create_dataset("g", tuple(N), np.float64)
            cp_q.create_dataset("observables",
                                (n_stash,) + tuple(N) + (n_obs,), np.float64)
            if self.save_rho:
                cp_q.create_dataset("rho", tuple(N) + (self.Nk,), np.float64)
            # the render grid + reduced observables are identical on every rank;
            # the head writes them once (write_slice is an independent write)
            if checkpoint is not None and rc.is_head:
                base = f"{path}/quad{i_quad}"
                checkpoint.write_slice(checkpoint[base + "/q"], (0, 0, 0),
                                       self._render_q[i_quad])
                checkpoint.write_slice(checkpoint[base + "/g"], (0, 0),
                                       self._render_g[i_quad])
                obs = torch.from_numpy(np.stack(self._stash_obs[i_quad], axis=0))
                checkpoint.write_slice(checkpoint[base + "/observables"],
                                       (0, 0, 0, 0), obs)
                if self.save_rho:
                    checkpoint.write_slice(checkpoint[base + "/rho"], (0, 0, 0),
                                           self._sample_grid(i_quad))
        self._stash_t, self._stash_i = [], []
        self._stash_obs = [[] for _ in self._render_q]
        return saved
