from __future__ import annotations
from typing import Optional

import numpy as np
import torch

from qimpy import TreeNode, rc, log
from qimpy.io import CheckpointPath, CheckpointContext
from qimpy.mpi import ProcessGrid
from ..material import Material
from . import TensorList, Geometry
from ._dg2d import DG2D, vandermonde2d
from ._dg_torch import AdvectTorch
from ._dg_mesh import load_mesh


class TriSet(Geometry):
    """Discontinuous-Galerkin geometry on an externally supplied triangle mesh.

    qimpy's spatial transport solver: a nodal DG advection operator on triangles
    (exact geometry, high order). The physics state ``rho`` lives on the DG
    nodes. The triangle mesh is NOT generated here -- it is produced by external
    tooling (Shewchuk's ``triangle``, gmsh, a hand graded/symmetric generator,
    ...) and supplied via ``mesh_file`` (see ``_dg_mesh.load_mesh`` for the
    format). Physical boundary faces are tagged in the mesh with marker names;
    a name matching a ``contacts`` key becomes that contact, anything else
    reflects. For checkpoint/plot output the DG field is sampled onto a
    structured bounding-box grid derived from the mesh.
    """

    dg: DG2D
    order: int

    def __init__(
        self,
        *,
        material: Material,
        mesh_file: str,
        contacts: dict[str, Optional[dict]],
        order: int = 3,
        render_grid_spacing: Optional[float] = None,
        save_rho: bool = False,
        process_grid: ProcessGrid,
        checkpoint_in: CheckpointPath = CheckpointPath(),
    ):
        """
        Parameters
        ----------
        mesh_file
            :yaml:`Path to an external triangle mesh (.npz) to solve on.`
            Generated by any external mesher; qimpy does not triangulate.
            Format: vertices (Nv,2), triangles (K,3), and optional
            boundary_edges (Nb,2) + boundary_markers (Nb,) naming each physical
            face ('wall' or a contact name), plus an optional periodic lattice.
        contacts
            :yaml:`Dictionary of contact names to parameters.`
            Names must match boundary markers in the mesh file.
        order
            :yaml:`Polynomial order N of the DG basis on each triangle.`
        render_grid_spacing
            :yaml:`Structured-grid spacing used only for checkpoint/plot output.`
        save_rho
            :yaml:`Whether to write the full density matrix at each checkpoint.`
        """
        TreeNode.__init__(self)
        self.material = material
        self.comm = process_grid.get_comm("r")
        self.order = order
        self.mesh_file = mesh_file
        self.save_rho = save_rho

        # --- mesh comes from an external file; qimpy does not generate it ---
        mesh = load_mesh(mesh_file)
        self.mesh = mesh
        dg = DG2D(order, mesh.VX, mesh.VY, mesh.EToV)
        # curve any boundary faces whose marker carries a projector (straight by
        # default for external meshes; projectors are None unless supplied)
        fm = mesh.face_markers(dg)
        by_marker: dict[int, list] = {}
        for (k, f), (name, mid) in fm.items():
            if mesh.projectors.get(mid) is not None:
                by_marker.setdefault(mid, []).append((k, f))
        for mid, faces in by_marker.items():
            dg.curve_boundary(faces, mesh.projectors[mid])
        if getattr(mesh, "_lattice", None):
            dg.make_periodic(mesh._lattice)
        self.dg = dg

        # --- channel velocities + DG advection RHS (torch) ---
        v = np.asarray(material.transport_velocity.detach().cpu().numpy(), float)
        self.Nk = v.shape[0]
        dtype = material.transport_velocity.dtype
        self._vx = torch.tensor(v[:, 0], device=rc.device, dtype=dtype)
        self._vy = torch.tensor(v[:, 1], device=rc.device, dtype=dtype)
        self.adv = AdvectTorch(dg, device=rc.device, dtype=dtype)
        self.dt_max = float(0.4 * dg.dt_scale
                            / max(np.hypot(v[:, 0], v[:, 1]).max(), 1e-300))

        # --- boundaries from mesh markers; structured render grid from mesh ---
        self.contacts = contacts
        self._setup_boundaries(dg, material, contacts)
        self._build_render_grid(render_grid_spacing)
        self._interp = [self._build_interp(q) for q in self._render_q]

        self._stash_t: list[float] = []
        self._stash_i: list[int] = []
        self._stash_obs: list[list[np.ndarray]] = [[] for _ in self._render_q]

        # --- initial density: material equilibrium tiled onto DG nodes ---
        # State evolved by the stepper is the conservative variable w = M_k u
        # (mass-weighted), so the conserved sum 1^T w never passes through M^-1.
        Nkbb = material.rho0.numel()
        rho0_nodal = material.rho0.flatten().to(rc.device).reshape(1, 1, Nkbb) \
            * torch.ones(dg.Np, dg.K, Nkbb, device=rc.device, dtype=dtype)
        self._rho = self.adv.apply_mass(rho0_nodal)

    # ------------------------------------------------------------------ #
    def _setup_boundaries(self, dg, material, contacts):
        """Classify physical boundary nodes into reflective vs contact patches
        using the mesh's boundary markers, and register the matching material
        operators with the advection engine. Periodic faces are already linked
        by make_periodic and are not in dg.mapB."""
        if dg.mapB.size == 0:
            return                                   # fully periodic: nothing to do
        # marker name for every boundary node, via its (element, local-face)
        fm = self.mesh.face_markers(dg)
        Nfp, Nfaces = dg.Nfp, dg.Nfaces
        node_name = np.empty(dg.mapB.size, dtype=object)
        for i, p in enumerate(dg.mapB):
            p = int(p); nfp = p % Nfp; t = p // Nfp
            f = t % Nfaces; k = t // Nfaces
            node_name[i] = fm.get((k, f), ("wall", 0))[0]

        n_all = self.adv.boundary_normals()          # (Nb, 2) outward unit normals
        contact_ops = []
        assigned = np.zeros(dg.mapB.size, bool)
        for name, params in (contacts or {}).items():
            sel = np.where(node_name == name)[0]
            if sel.size == 0:
                continue
            assigned[sel] = True
            kw = dict(params) if params else {}
            ten = torch.as_tensor(sel, device=rc.device, dtype=torch.long)
            contact_ops.append((sel, material.get_contactor(n_all[ten], **kw)))
        reflect_sel = np.where(~assigned)[0]          # everything else reflects
        reflector = None
        spec = float(getattr(material, "specularity", 1.0))
        if reflect_sel.size:
            ten = torch.as_tensor(reflect_sel, device=rc.device, dtype=torch.long)
            saved = getattr(material, "specularity", None)
            try:
                if saved is not None:
                    material.specularity = 1.0
                reflector = material.get_reflector(n_all[ten])
            finally:
                if saved is not None:
                    material.specularity = saved
        self.adv.set_boundary(reflect_sel=reflect_sel, reflector=reflector,
                              contacts=contact_ops, specularity=spec)
        log.info(
            f"tri_set boundaries: {reflect_sel.size} reflective + "
            f"{sum(s.size for s, _ in contact_ops)} contact nodes")

    # ------------------------------------------------------------------ #
    def _build_render_grid(self, render_grid_spacing):
        """Structured bounding-box grid over the mesh, for checkpoint/plot output
        (single 'quad'). Cells outside the triangulated domain are masked."""
        dg = self.dg
        xmin, xmax = float(dg.VX.min()), float(dg.VX.max())
        ymin, ymax = float(dg.VY.min()), float(dg.VY.max())
        span = max(xmax - xmin, ymax - ymin)
        gs = render_grid_spacing if render_grid_spacing else span / 150.0
        nx = max(2, int(np.ceil((xmax - xmin) / gs)))
        ny = max(2, int(np.ceil((ymax - ymin) / gs)))
        dx = (xmax - xmin) / nx; dy = (ymax - ymin) / ny
        xg = xmin + (np.arange(nx) + 0.5) * dx
        yg = ymin + (np.arange(ny) + 0.5) * dy
        X, Y = np.meshgrid(xg, yg, indexing="ij")
        q = torch.from_numpy(np.stack([X, Y], axis=-1)).to(rc.device)
        g = torch.full((nx, ny), dx * dy, device=rc.device, dtype=torch.float64)
        self._render_q = [q]
        self._render_g = [g]
        self._render_size = [(nx, ny)]
        self._bbox = (xmin, xmax, ymin, ymax)

    def _build_interp(self, q_grid):
        """Locate each render point in a triangle and build DG nodal-interp
        weights; flag points outside the mesh so they can be masked."""
        dg = self.dg
        q = q_grid.detach().cpu().numpy().reshape(-1, 2)
        A = np.stack([dg.VX[dg.EToV[:, 0]], dg.VY[dg.EToV[:, 0]]], axis=1)
        B = np.stack([dg.VX[dg.EToV[:, 1]], dg.VY[dg.EToV[:, 1]]], axis=1)
        C = np.stack([dg.VX[dg.EToV[:, 2]], dg.VY[dg.EToV[:, 2]]], axis=1)
        Minv = np.linalg.inv(np.stack([B - A, C - A], axis=-1))
        VinvT = np.linalg.inv(dg.V).T
        tri = np.empty(len(q), int); W = np.empty((len(q), dg.Np))
        inside = np.empty(len(q), bool)
        for p in range(len(q)):
            bc = np.einsum('kij,kj->ki', Minv, q[p][None, :] - A)
            b1 = 1.0 - bc.sum(1)
            score = np.minimum.reduce([b1, bc[:, 0], bc[:, 1]])
            k = int(np.argmax(score))
            inside[p] = score[k] >= -1e-9
            b = np.array([bc[k, 0], bc[k, 1], 1.0 - bc[k].sum()])
            if score[k] < 0.0:
                b = np.clip(b, 0.0, None); b = b / b.sum()
            vrow = vandermonde2d(dg.N, np.array([2 * b[0] - 1]),
                                 np.array([2 * b[1] - 1]))[0]
            tri[p] = k; W[p] = VinvT @ vrow
        return tri, W, inside

    def _sample_grid(self, i_quad):
        rho = self.density.detach().cpu().numpy()    # density u = M^-1 w
        tri, W, inside = self._interp[i_quad]
        grid = np.einsum('pi,ipk->pk', W, rho[:, tri, :])
        grid[~inside] = np.nan                        # mask outside the domain
        return torch.from_numpy(
            grid.reshape(*self._render_size[i_quad], -1)).to(self._rho)

    # ---- qimpy Geometry contract ----
    @property
    def rho(self) -> TensorList:
        return TensorList([self._rho])

    @rho.setter
    def rho(self, rho_new: TensorList) -> None:
        self._rho = rho_new[0]

    @property
    def density(self) -> torch.Tensor:
        """Nodal density u = M_k^{-1} w recovered from the conservative state."""
        return self.adv.apply_mass_inv(self._rho)

    @density.setter
    def density(self, dens: torch.Tensor) -> None:
        """Set the state from a nodal density: w = M_k u."""
        self._rho = self.adv.apply_mass(dens.to(self._rho))

    def rho_dot(self, rho: TensorList, t: float) -> TensorList:
        w = rho[0]
        # Advection of the conservative variable: dw/dt = vol - surf (no inverse
        # in the conserved direction -> 1^T w conserved to round-off).
        spatial = self.adv.rhs_w(w, self._vx, self._vy, t)
        # Collisions act on the density; map their dn/dt back to w-space via M.
        u = self.adv.apply_mass_inv(w)
        coll_u = self.material.rho_dot(
            u.reshape(-1, 1, self.Nk), t, id(self)).reshape(u.shape)
        coll = self.adv.apply_mass(coll_u)
        return TensorList([spatial + coll])

    def update_stash(self, i_step: int, t: float) -> None:
        self._stash_i.append(i_step); self._stash_t.append(t)
        for i_quad in range(len(self._render_q)):
            obs = self.material.measure_observables(self._sample_grid(i_quad), t)
            self._stash_obs[i_quad].append(obs.detach().cpu().numpy())

    def _save_checkpoint(
        self, cp_path: CheckpointPath, context: CheckpointContext
    ) -> list[str]:
        attrs = cp_path.attrs
        attrs["mesh_file"] = self.mesh_file
        attrs["geometry_type"] = "tri_set"
        attrs["dg_order"] = self.order
        xmin, xmax, ymin, ymax = self._bbox
        # single synthetic quad = bounding box, so the existing plot pipeline
        # (which loops over quads) reads one rectangular render block
        quads = np.array([[[xmin, ymin], [xmax, ymin], [xmax, ymax], [xmin, ymax]]])
        verts = quads.reshape(-1, 2)
        saved = [
            cp_path.write("vertices", torch.from_numpy(verts)),
            cp_path.write("quads", torch.from_numpy(quads)),
            cp_path.write("displacements",
                          torch.from_numpy(np.zeros((1, 4, 2)))),
            cp_path.write("adjacency",
                          torch.from_numpy(-np.ones((1, 4), int))),
            cp_path.write("grid_size",
                          torch.from_numpy(np.array([self._render_size[0]], int))),
            cp_path.write("contacts", torch.from_numpy(np.zeros((0, 3)))),
            cp_path.write("apertures", torch.from_numpy(np.zeros((0, 3)))),
            "q", "g", "observables",
        ]
        cp_path.write_str("contact_names", ",".join(self.contacts.keys()))
        cp_path.write_str("aperture_names", "")
        cp_path.write_str("observable_names",
                          ",".join(self.material.get_observable_names()))
        cp_path["t"] = np.array(self._stash_t)
        cp_path["i_step"] = np.array(self._stash_i)
        n_obs = len(self.material.get_observable_names())
        n_stash = len(self._stash_t)
        checkpoint, path = cp_path
        for i_quad in range(len(self._render_size)):
            cp_q = CheckpointPath(checkpoint, f"{path}/quad{i_quad}")
            N = self._render_size[i_quad]
            cp_q.create_dataset("q", tuple(N) + (2,), np.float64)
            cp_q.create_dataset("g", tuple(N), np.float64)
            cp_q.create_dataset("observables",
                                (n_stash,) + tuple(N) + (n_obs,), np.float64)
            if self.save_rho:
                cp_q.create_dataset("rho", tuple(N) + (self.Nk,), np.float64)
            if checkpoint is not None and self.material.comm.rank == 0:
                base = f"{path}/quad{i_quad}"
                checkpoint.write_slice(checkpoint[base + "/q"], (0, 0, 0),
                                       self._render_q[i_quad])
                checkpoint.write_slice(checkpoint[base + "/g"], (0, 0),
                                       self._render_g[i_quad])
                obs = torch.from_numpy(np.stack(self._stash_obs[i_quad], axis=0))
                checkpoint.write_slice(checkpoint[base + "/observables"],
                                       (0, 0, 0, 0), obs)
                if self.save_rho:
                    checkpoint.write_slice(checkpoint[base + "/rho"], (0, 0, 0),
                                           self._sample_grid(i_quad))
        self._stash_t, self._stash_i = [], []
        self._stash_obs = [[] for _ in self._render_q]
        return saved
