from __future__ import annotations
from collections import Counter

import pytest
import torch
import numpy as np

from qimpy import rc
from ._dg_mesh import save_mesh


# ----------------------------------------------------------------------------
# qimpy no longer meshes: the mesh is generated by external tooling and passed
# as a file. These helpers play that role for the tests (Shewchuk's `triangle`).
# ----------------------------------------------------------------------------
def _make_rect_mesh(grid_spacing: float, path: str, all_walls: bool = False) -> str:
    """External rect-domain mesh [5,105]x[5,55] with source/drain contact faces,
    written in the format TriSet consumes. Mirrors examples/.../rect-domain.svg.
    With all_walls=True every boundary edge is marked a (reflective) wall, giving
    a closed domain with no contact/outflow faces."""
    import triangle as tr
    pts = np.array([[5, 5], [105, 5], [105, 55], [5, 55]], float)
    seg = np.array([[0, 1], [1, 2], [2, 3], [3, 0]])
    m = tr.triangulate({"vertices": pts, "segments": seg},
                       f"pq30a{grid_spacing ** 2:g}")
    V, T = m["vertices"], m["triangles"]
    ec: Counter = Counter()
    for t in T:
        for x, y in [(0, 1), (1, 2), (2, 0)]:
            ec[tuple(sorted((int(t[x]), int(t[y]))))] += 1
    be = [e for e, c in ec.items() if c == 1]
    SRC, DRN = (10.0, 55.0, 5.0), (10.0, 5.0, 5.0)
    if all_walls:
        bm = ["wall"] * len(be)
    else:
        bm = []
        for a, b in be:
            mx, my = 0.5 * (V[a] + V[b])
            if (mx - SRC[0]) ** 2 + (my - SRC[1]) ** 2 <= SRC[2] ** 2:
                bm.append("source")
            elif (mx - DRN[0]) ** 2 + (my - DRN[1]) ** 2 <= DRN[2] ** 2:
                bm.append("drain")
            else:
                bm.append("wall")
    save_mesh(path, V, T, np.array(be), bm)
    return path


def _make_periodic_rect(n: int, L: float, path: str) -> str:
    """Structured n x n triangulation of [0,L]^2 with periodic lattice vectors.
    A structured grid guarantees opposite-edge nodes match under translation, so
    DG2D.make_periodic links every boundary face into a fully periodic domain."""
    xs = np.linspace(0.0, L, n + 1)
    V = np.array([[x, y] for y in xs for x in xs], float)

    def idx(i, j):
        return j * (n + 1) + i

    T, be = [], []
    for j in range(n):
        for i in range(n):
            a, b = idx(i, j), idx(i + 1, j)
            c, d = idx(i + 1, j + 1), idx(i, j + 1)
            T += [[a, b, c], [a, c, d]]
    for i in range(n):
        be += [[idx(i, 0), idx(i + 1, 0)], [idx(i, n), idx(i + 1, n)]]
    for j in range(n):
        be += [[idx(0, j), idx(0, j + 1)], [idx(n, j), idx(n, j + 1)]]
    save_mesh(path, V, np.array(T), np.array(be), ["periodic"] * len(be),
              lattice=[[L, 0.0], [0.0, L]])
    return path


def _make_strip_mesh(nx: int, ny: int, Lx: float, Ly: float,
                     alpha_deg: float, path: str) -> str:
    """Tilted strip:  the [0,Lx] x [0,Ly] reference rectangle is rotated by
    alpha so the top/bottom walls become OBLIQUE (normal at angle 90+alpha
    from x-axis), and the periodic lattice vector becomes (Lx cos a, Lx sin a)
    along the long direction.

    Why tilt?  At axis-aligned walls (alpha = 0 -> normal = +/- y_hat) the
    discrete reflection happens to coincide with a Galerkin operator by
    symmetry, so the alias-driven tang-quadrature artifact at finite N_theta
    cancels even without the (D, T) correction.  At any other angle the
    artifact does not cancel and the test discriminates the (D, T) fix from
    the older single-D scheme.

    The wall-tangential direction is (cos a, sin a) at every wall, and
    periodic boundaries don't mix angular moments, so
        J_tang = cos(a) * jx_total + sin(a) * jy_total
    is the global invariant of specular reflection on this geometry."""
    a = np.deg2rad(alpha_deg)
    c, s = np.cos(a), np.sin(a)
    xs = np.linspace(0.0, Lx, nx + 1)
    ys = np.linspace(0.0, Ly, ny + 1)
    V  = np.array([[x * c - y * s, x * s + y * c]
                   for y in ys for x in xs], float)
    def idx(i, j): return j * (nx + 1) + i
    T = []
    for j in range(ny):
        for i in range(nx):
            a_, b_ = idx(i, j), idx(i + 1, j)
            c_, d_ = idx(i + 1, j + 1), idx(i, j + 1)
            T += [[a_, b_, c_], [a_, c_, d_]]
    be, bm = [], []
    for i in range(nx):
        be.append([idx(i, 0),  idx(i + 1, 0)]);  bm.append("wall")
        be.append([idx(i, ny), idx(i + 1, ny)]); bm.append("wall")
    for j in range(ny):
        be.append([idx(0,  j), idx(0,  j + 1)]); bm.append("periodic")
        be.append([idx(nx, j), idx(nx, j + 1)]); bm.append("periodic")
    save_mesh(path, V, np.array(T), np.array(be), bm,
              lattice=[[Lx * c, Lx * s]])
    return path


def _step_rk4(g, dt, nt, t0=0.0):
    for it in range(nt):
        r0 = g.rho; t = t0 + it * dt
        k1 = g.rho_dot(r0, t); k2 = g.rho_dot(r0 + (0.5 * dt) * k1, t + 0.5 * dt)
        k3 = g.rho_dot(r0 + (0.5 * dt) * k2, t + 0.5 * dt)
        k4 = g.rho_dot(r0 + dt * k3, t + dt)
        g.rho = r0 + (dt / 6.0) * (k1 + 2 * (k2 + k3) + k4)


def test_reflective_conservation(tmp_path):
    """Specular reflective walls conserve the density (m=0 channel) to ~machine
    precision over many steps, including the regime where the blob reaches the
    walls and actively reflects. Uses an all-wall (closed) mesh -- the default
    rect mesh has source/drain faces that default to outflow when contacts={},
    in which case mass is *physically* lost through them. Sums only channel 0:
    the higher modal channels (currents) are not conserved, so summing the full
    state would conflate non-conservation of currents with mass leakage."""
    from .._transport import Transport
    rc.init()
    mesh = _make_rect_mesh(8.0, str(tmp_path / "rect.npz"), all_walls=True)
    transport = Transport(
        fermi_surface=dict(kF=1.0, vF=1.5, M_theta=8, Nr=1, T=1.0,
                           tau_p=np.inf, tau_ee=np.inf, r_c=np.inf,
                           specularity=1.0),
        tri_set=dict(mesh_file=mesh, contacts={}, order=3),
        time_evolution=dict(t_max=1.0, dt_save=2.0, n_collate=10),
    )
    g = transport.geometry; dg = g.dg
    q = np.stack([dg.x, dg.y], axis=-1); q0 = np.array([55.0, 30.0])
    blob = np.exp(-(((q - q0) ** 2).sum(-1)) / (2 * 6.0 ** 2))
    if transport.material.comm.rank == 0:
        # Delta-k storage: a constant-in-theta nodal state corresponds to the
        # (m=0) angular mode = density blob.  Broadcast across all N_theta channels.
        dens = torch.zeros_like(g.density)
        dens[:, :, :] = torch.as_tensor(blob).to(dens).unsqueeze(-1)
        g.density = dens

    def total_mass():
        # The conserved quantity is the integral of the density observable n,
        # which is the radial-and-angular weighted sum of all delta-k channels.
        u = g.dist.adv.apply_mass_inv(g._rho)
        obs = transport.material.measure_observables(u, 0.0)   # (Np, K, 3)
        return float(dg.integrate(np.asarray(obs[..., 0])))

    m0 = total_mass()
    dt = 0.5 * g.dt_max
    # Long enough for the blob to traverse the domain and actively reflect off
    # walls (vF=1.5, domain ~100x50): ~30 time units = several wall encounters.
    _step_rk4(g, dt, int(30.0 / dt))
    assert abs(total_mass() - m0) / abs(m0) < 1e-10, \
        "reflective walls not conserving mass"


def test_strip_tang_momentum_conservation(tmp_path):
    """Long-time integration on a TILTED strip (oblique walls + periodic along
    the slanted direction) -- the projected current
        J_tang = cos(alpha) * jx + sin(alpha) * jy
    is a global invariant of specular reflection on this geometry, because
    every wall has tangent direction (cos a, sin a) and the periodic boundary
    transports across it without mixing angular moments.

    With the (D, T) reflector this conservation holds to roundoff over
    thousands of RK4 steps and several wall bounces.  With the old single-D
    scheme the discrete tang-quadrature artifact at oblique walls accumulates
    into a drift of ~1e-4 over the same span (mass still conserved by D),
    confirmed empirically -- this test reliably discriminates the two.

    Mass is checked as a stronger control: the D coefficient guarantees it
    even in the single-D scheme, so passing this isn't surprising; failing
    it would be."""
    from .._transport import Transport
    rc.init()
    alpha_deg = 23.7                              # oblique; not at 0, 45, 90 deg
    a = np.deg2rad(alpha_deg)
    ca, sa = float(np.cos(a)), float(np.sin(a))
    Lx, Ly = 40.0, 20.0
    mesh = _make_strip_mesh(8, 4, Lx, Ly, alpha_deg,
                            str(tmp_path / "strip.npz"))
    transport = Transport(
        fermi_surface=dict(kF=1.0, vF=1.5, M_theta=8, Nr=1, T=1.0,
                           tau_p=np.inf, tau_ee=np.inf, r_c=np.inf,
                           specularity=1.0),
        tri_set=dict(mesh_file=mesh, contacts={}, order=3),
        time_evolution=dict(t_max=1.0, dt_save=2.0, n_collate=10),
    )
    g = transport.geometry; dg = g.dg
    # IC in delta-k:  density bump centered on the strip midline (in the
    # rotated-perpendicular coord) + a uniform drift along the wall-tangent
    # direction.  The angular profile cos(theta - alpha) projects directly
    # onto the wall-tangent component, giving a nonzero J_tang.
    x = np.asarray(dg.x); y = np.asarray(dg.y)
    d_perp = -sa * x + ca * y - 0.5 * Ly         # perp-to-strip coord
    blob = np.exp(-(d_perp ** 2) / (2 * 2.0 ** 2))
    theta_q = transport.material.angular.theta.detach().cpu().numpy()
    cos_t_a = np.cos(theta_q - a)
    if transport.material.comm.rank == 0:
        A, B = 1.0, 0.3
        u_init = A * blob[..., None] + B * cos_t_a[None, None, :]
        g.density = torch.as_tensor(u_init.astype(np.float64)).to(g.density)

    def total(obs_idx):
        u = g.dist.adv.apply_mass_inv(g._rho)
        obs = transport.material.measure_observables(u, 0.0)
        return float(dg.integrate(np.asarray(obs[..., obs_idx])))

    n0  = total(0)
    J0  = ca * total(1) + sa * total(2)
    dt = 0.5 * g.dt_max
    # vF=1.5, Ly=20: perpendicular transit time ~13;  t_end=20 covers
    # roughly one full round-trip after the gas has reached steady drift.
    _step_rk4(g, dt, int(20.0 / dt))
    n1 = total(0)
    J1 = ca * total(1) + sa * total(2)
    assert abs(n1 - n0) / abs(n0) < 1e-10, \
        f"strip mass drifted: dn/n0 = {(n1-n0)/n0:.2e}"
    assert abs(J1 - J0) / abs(J0) < 1e-10, \
        f"strip wall-tangent current J_tang drifted: dJ/J0 = {(J1-J0)/J0:.2e}"


def test_contact_steady_state(tmp_path):
    """Source/drain contacts (dmu=+/-0.1) drive a stable, bounded steady state."""
    from .._transport import Transport
    rc.init()
    mesh = _make_rect_mesh(8.0, str(tmp_path / "rect.npz"))
    transport = Transport(
        fermi_surface=dict(kF=1.0, vF=1.5, M_theta=8, Nr=1, T=1.0,
                           tau_p=np.inf, tau_ee=np.inf, r_c=np.inf,
                           specularity=1.0),
        tri_set=dict(mesh_file=mesh,
                     contacts={"source": {"dmu": 0.1}, "drain": {"dmu": -0.1}},
                     order=3),
        time_evolution=dict(t_max=1.0, dt_save=2.0, n_collate=10),
    )
    g = transport.geometry
    if transport.material.comm.rank == 0:
        g.density = torch.zeros_like(g.density)
    dt = 0.5 * g.dt_max
    _step_rk4(g, dt, int(50.0 / dt))
    pot = g.density[..., 0]                    # modal density = m=0 coefficient
    assert torch.isfinite(pot).all(), "contact-driven solution diverged"
    assert float(pot.abs().max()) < 0.15, "interior potential exceeds contact range"


@pytest.mark.skip(reason="Curved isoparametric boundaries require arc projectors "
                         "in the external mesh format; not yet supported since "
                         "meshing moved out of qimpy.")
def test_curved_mass_conservation():
    ...


def test_spatial_mpi_matches_serial(tmp_path):
    """Spatial domain decomposition reproduces the serial DG result bit-for-bit
    on a contact-driven problem (halo emulated in-process; the real mpi4py
    transport moves the identical buffers)."""
    from qimpy.mpi import ProcessGrid
    from qimpy.transport.material import FermiSurface
    from ._dg_mesh import load_mesh
    from ._dg2d import DG2D
    from ._dg_mpi import (compute_partition, SpatialPartition,
                          DistributedAdvect, emulate_halo)
    rc.init()
    torch.set_default_dtype(torch.float64)
    mesh = load_mesh(_make_rect_mesh(8.0, str(tmp_path / "rect.npz")))
    pg = ProcessGrid(rc.comm, "rk", (1, 1))           # all channels local (scalar/coupled: Pk=1)
    mat = FermiSurface(kF=1.0, vF=1.5, M_theta=8, Nr=1, T=1.0,
                       tau_p=np.inf, tau_ee=np.inf, r_c=np.inf,
                       specularity=1.0, process_grid=pg)
    contacts = {"source": {"dmu": 0.1}, "drain": {"dmu": -0.1}}
    order, nsteps = 2, 16
    dt = 0.5 * float(DG2D(order, mesh.VX, mesh.VY, mesh.EToV).dt_scale) / 1.5

    def initial(adv, dg):
        x, y = np.asarray(dg.x), np.asarray(dg.y)
        u0 = np.zeros((dg.Np, dg.K, adv.Nk))
        # Delta-k constant-in-theta = (m=0) density blob.  Broadcast across channels.
        u0[:, :, :] = np.exp(
            -((x - 55) ** 2 + (y - 30) ** 2) / (2 * 8.0 ** 2)
        )[:, :, None]
        return adv.adv.apply_mass(torch.from_numpy(u0))

    def run(nparts):
        part = compute_partition(mesh, nparts)
        parts = [SpatialPartition(mesh, order, part, r) for r in range(nparts)]
        advs = [DistributedAdvect(p, mat, contacts) for p in parts]
        ws = [initial(advs[r], parts[r].dg) for r in range(nparts)]

        def rhs(stage):
            emulate_halo(parts, stage)
            return [advs[r].local_rhs(stage[r]) for r in range(nparts)]

        for _ in range(nsteps):
            k1 = rhs([w.clone() for w in ws])
            k2 = rhs([ws[r] + 0.5 * dt * k1[r] for r in range(nparts)])
            k3 = rhs([ws[r] + 0.5 * dt * k2[r] for r in range(nparts)])
            k4 = rhs([ws[r] + dt * k3[r] for r in range(nparts)])
            ws = [ws[r] + (dt / 6.0) * (k1[r] + 2 * (k2[r] + k3[r]) + k4[r])
                  for r in range(nparts)]
        K = len(mesh.EToV)
        full = np.zeros((parts[0].dg.Np, K, advs[0].Nk))
        for r in range(nparts):
            no = parts[r].n_owned
            full[:, parts[r].local2global_elem[:no], :] = \
                ws[r].detach().cpu().numpy()[:, :no, :]
        return full

    serial, par = run(1), run(4)
    assert np.abs(par - serial).max() < 1e-12, "spatial decomposition != serial"
