from __future__ import annotations
from collections import Counter

import pytest
import torch
import numpy as np

from qimpy import rc
from ._dg_mesh import save_mesh


# ----------------------------------------------------------------------------
# qimpy no longer meshes: the mesh is generated by external tooling and passed
# as a file. These helpers play that role for the tests (Shewchuk's `triangle`).
# ----------------------------------------------------------------------------
def _make_rect_mesh(grid_spacing: float, path: str, all_walls: bool = False) -> str:
    """External rect-domain mesh [5,105]x[5,55] with source/drain contact faces,
    written in the format TriSet consumes. Mirrors examples/.../rect-domain.svg.
    With all_walls=True every boundary edge is marked a (reflective) wall, giving
    a closed domain with no contact/outflow faces."""
    import triangle as tr
    pts = np.array([[5, 5], [105, 5], [105, 55], [5, 55]], float)
    seg = np.array([[0, 1], [1, 2], [2, 3], [3, 0]])
    m = tr.triangulate({"vertices": pts, "segments": seg},
                       f"pq30a{grid_spacing ** 2:g}")
    V, T = m["vertices"], m["triangles"]
    ec: Counter = Counter()
    for t in T:
        for x, y in [(0, 1), (1, 2), (2, 0)]:
            ec[tuple(sorted((int(t[x]), int(t[y]))))] += 1
    be = [e for e, c in ec.items() if c == 1]
    SRC, DRN = (10.0, 55.0, 5.0), (10.0, 5.0, 5.0)
    if all_walls:
        bm = ["wall"] * len(be)
    else:
        bm = []
        for a, b in be:
            mx, my = 0.5 * (V[a] + V[b])
            if (mx - SRC[0]) ** 2 + (my - SRC[1]) ** 2 <= SRC[2] ** 2:
                bm.append("source")
            elif (mx - DRN[0]) ** 2 + (my - DRN[1]) ** 2 <= DRN[2] ** 2:
                bm.append("drain")
            else:
                bm.append("wall")
    save_mesh(path, V, T, np.array(be), bm)
    return path


def _make_periodic_rect(n: int, L: float, path: str) -> str:
    """Structured n x n triangulation of [0,L]^2 with periodic lattice vectors.
    A structured grid guarantees opposite-edge nodes match under translation, so
    DG2D.make_periodic links every boundary face into a fully periodic domain."""
    xs = np.linspace(0.0, L, n + 1)
    V = np.array([[x, y] for y in xs for x in xs], float)

    def idx(i, j):
        return j * (n + 1) + i

    T, be = [], []
    for j in range(n):
        for i in range(n):
            a, b = idx(i, j), idx(i + 1, j)
            c, d = idx(i + 1, j + 1), idx(i, j + 1)
            T += [[a, b, c], [a, c, d]]
    for i in range(n):
        be += [[idx(i, 0), idx(i + 1, 0)], [idx(i, n), idx(i + 1, n)]]
    for j in range(n):
        be += [[idx(0, j), idx(0, j + 1)], [idx(n, j), idx(n, j + 1)]]
    save_mesh(path, V, np.array(T), np.array(be), ["periodic"] * len(be),
              lattice=[[L, 0.0], [0.0, L]])
    return path


def _step_rk4(g, dt, nt, t0=0.0):
    for it in range(nt):
        r0 = g.rho; t = t0 + it * dt
        k1 = g.rho_dot(r0, t); k2 = g.rho_dot(r0 + (0.5 * dt) * k1, t + 0.5 * dt)
        k3 = g.rho_dot(r0 + (0.5 * dt) * k2, t + 0.5 * dt)
        k4 = g.rho_dot(r0 + dt * k3, t + dt)
        g.rho = r0 + (dt / 6.0) * (k1 + 2 * (k2 + k3) + k4)


def test_reflective_conservation(tmp_path):
    """Specular reflective walls conserve the density (m=0 channel) to ~machine
    precision over many steps, including the regime where the blob reaches the
    walls and actively reflects. Uses an all-wall (closed) mesh -- the default
    rect mesh has source/drain faces that default to outflow when contacts={},
    in which case mass is *physically* lost through them. Sums only channel 0:
    the higher modal channels (currents) are not conserved, so summing the full
    state would conflate non-conservation of currents with mass leakage."""
    from .._transport import Transport
    rc.init()
    mesh = _make_rect_mesh(8.0, str(tmp_path / "rect.npz"), all_walls=True)
    transport = Transport(
        fermi_surface=dict(kF=1.0, vF=1.5, M_theta=8, Nr=1, T=1.0,
                           tau_p=np.inf, tau_ee=np.inf, r_c=np.inf,
                           specularity=1.0),
        tri_set=dict(mesh_file=mesh, contacts={}, order=3),
        time_evolution=dict(t_max=1.0, dt_save=2.0, n_collate=10),
    )
    g = transport.geometry; dg = g.dg
    q = np.stack([dg.x, dg.y], axis=-1); q0 = np.array([55.0, 30.0])
    blob = np.exp(-(((q - q0) ** 2).sum(-1)) / (2 * 6.0 ** 2))
    if transport.material.comm.rank == 0:
        # Delta-k storage: a constant-in-theta nodal state corresponds to the
        # (m=0) angular mode = density blob.  Broadcast across all N_theta channels.
        dens = torch.zeros_like(g.density)
        dens[:, :, :] = torch.as_tensor(blob).to(dens).unsqueeze(-1)
        g.density = dens

    def total_mass():
        # The conserved quantity is the integral of the density observable n,
        # which is the radial-and-angular weighted sum of all delta-k channels.
        u = g.dist.adv.apply_mass_inv(g._rho)
        obs = transport.material.measure_observables(u, 0.0)   # (Np, K, 3)
        return float(dg.integrate(np.asarray(obs[..., 0])))

    m0 = total_mass()
    dt = 0.5 * g.dt_max
    # Long enough for the blob to traverse the domain and actively reflect off
    # walls (vF=1.5, domain ~100x50): ~30 time units = several wall encounters.
    _step_rk4(g, dt, int(30.0 / dt))
    assert abs(total_mass() - m0) / abs(m0) < 1e-10, \
        "reflective walls not conserving mass"


def test_contact_steady_state(tmp_path):
    """Source/drain contacts (dmu=+/-0.1) drive a stable, bounded steady state."""
    from .._transport import Transport
    rc.init()
    mesh = _make_rect_mesh(8.0, str(tmp_path / "rect.npz"))
    transport = Transport(
        fermi_surface=dict(kF=1.0, vF=1.5, M_theta=8, Nr=1, T=1.0,
                           tau_p=np.inf, tau_ee=np.inf, r_c=np.inf,
                           specularity=1.0),
        tri_set=dict(mesh_file=mesh,
                     contacts={"source": {"dmu": 0.1}, "drain": {"dmu": -0.1}},
                     order=3),
        time_evolution=dict(t_max=1.0, dt_save=2.0, n_collate=10),
    )
    g = transport.geometry
    if transport.material.comm.rank == 0:
        g.density = torch.zeros_like(g.density)
    dt = 0.5 * g.dt_max
    _step_rk4(g, dt, int(50.0 / dt))
    pot = g.density[..., 0]                    # modal density = m=0 coefficient
    assert torch.isfinite(pot).all(), "contact-driven solution diverged"
    assert float(pot.abs().max()) < 0.15, "interior potential exceeds contact range"


@pytest.mark.skip(reason="Curved isoparametric boundaries require arc projectors "
                         "in the external mesh format; not yet supported since "
                         "meshing moved out of qimpy.")
def test_curved_mass_conservation():
    ...


def test_spatial_mpi_matches_serial(tmp_path):
    """Spatial domain decomposition reproduces the serial DG result bit-for-bit
    on a contact-driven problem (halo emulated in-process; the real mpi4py
    transport moves the identical buffers)."""
    from qimpy.mpi import ProcessGrid
    from qimpy.transport.material import FermiSurface
    from ._dg_mesh import load_mesh
    from ._dg2d import DG2D
    from ._dg_mpi import (compute_partition, SpatialPartition,
                          DistributedAdvect, emulate_halo)
    rc.init()
    torch.set_default_dtype(torch.float64)
    mesh = load_mesh(_make_rect_mesh(8.0, str(tmp_path / "rect.npz")))
    pg = ProcessGrid(rc.comm, "rk", (1, 1))           # all channels local (scalar/coupled: Pk=1)
    mat = FermiSurface(kF=1.0, vF=1.5, M_theta=8, Nr=1, T=1.0,
                       tau_p=np.inf, tau_ee=np.inf, r_c=np.inf,
                       specularity=1.0, process_grid=pg)
    contacts = {"source": {"dmu": 0.1}, "drain": {"dmu": -0.1}}
    order, nsteps = 2, 16
    dt = 0.5 * float(DG2D(order, mesh.VX, mesh.VY, mesh.EToV).dt_scale) / 1.5

    def initial(adv, dg):
        x, y = np.asarray(dg.x), np.asarray(dg.y)
        u0 = np.zeros((dg.Np, dg.K, adv.Nk))
        # Delta-k constant-in-theta = (m=0) density blob.  Broadcast across channels.
        u0[:, :, :] = np.exp(
            -((x - 55) ** 2 + (y - 30) ** 2) / (2 * 8.0 ** 2)
        )[:, :, None]
        return adv.adv.apply_mass(torch.from_numpy(u0))

    def run(nparts):
        part = compute_partition(mesh, nparts)
        parts = [SpatialPartition(mesh, order, part, r) for r in range(nparts)]
        advs = [DistributedAdvect(p, mat, contacts) for p in parts]
        ws = [initial(advs[r], parts[r].dg) for r in range(nparts)]

        def rhs(stage):
            emulate_halo(parts, stage)
            return [advs[r].local_rhs(stage[r]) for r in range(nparts)]

        for _ in range(nsteps):
            k1 = rhs([w.clone() for w in ws])
            k2 = rhs([ws[r] + 0.5 * dt * k1[r] for r in range(nparts)])
            k3 = rhs([ws[r] + 0.5 * dt * k2[r] for r in range(nparts)])
            k4 = rhs([ws[r] + dt * k3[r] for r in range(nparts)])
            ws = [ws[r] + (dt / 6.0) * (k1[r] + 2 * (k2[r] + k3[r]) + k4[r])
                  for r in range(nparts)]
        K = len(mesh.EToV)
        full = np.zeros((parts[0].dg.Np, K, advs[0].Nk))
        for r in range(nparts):
            no = parts[r].n_owned
            full[:, parts[r].local2global_elem[:no], :] = \
                ws[r].detach().cpu().numpy()[:, :no, :]
        return full

    serial, par = run(1), run(4)
    assert np.abs(par - serial).max() < 1e-12, "spatial decomposition != serial"
