from __future__ import annotations
from typing import Optional, Sequence
from collections import Counter
import argparse
import os
import tempfile

import pytest
import torch
import numpy as np
import matplotlib.pyplot as plt

from qimpy import log, rc
from qimpy.io import log_config
from qimpy.profiler import StopWatch
from .. import Transport
from ._dg_mesh import save_mesh


# ----------------------------------------------------------------------------
# qimpy no longer meshes: the mesh is generated by external tooling and passed
# as a file. These helpers play that role for the tests (Shewchuk's `triangle`).
# ----------------------------------------------------------------------------
def _make_rect_mesh(grid_spacing: float, path: str) -> str:
    """External rect-domain mesh [5,105]x[5,55] with source/drain contact faces,
    written in the format TriSet consumes. Mirrors examples/.../rect-domain.svg."""
    import triangle as tr
    pts = np.array([[5, 5], [105, 5], [105, 55], [5, 55]], float)
    seg = np.array([[0, 1], [1, 2], [2, 3], [3, 0]])
    m = tr.triangulate({"vertices": pts, "segments": seg},
                       f"pq30a{grid_spacing ** 2:g}")
    V, T = m["vertices"], m["triangles"]
    ec: Counter = Counter()
    for t in T:
        for x, y in [(0, 1), (1, 2), (2, 0)]:
            ec[tuple(sorted((int(t[x]), int(t[y]))))] += 1
    be = [e for e, c in ec.items() if c == 1]
    SRC, DRN = (10.0, 55.0, 5.0), (10.0, 5.0, 5.0)
    bm = []
    for a, b in be:
        mx, my = 0.5 * (V[a] + V[b])
        if (mx - SRC[0]) ** 2 + (my - SRC[1]) ** 2 <= SRC[2] ** 2:
            bm.append("source")
        elif (mx - DRN[0]) ** 2 + (my - DRN[1]) ** 2 <= DRN[2] ** 2:
            bm.append("drain")
        else:
            bm.append("wall")
    save_mesh(path, V, T, np.array(be), bm)
    return path


def gaussian_blob(
    q: torch.Tensor, q0: torch.Tensor, Rbasis: torch.Tensor, sigma: float
) -> torch.Tensor:
    dq = q - q0
    dq -= torch.floor(0.5 + dq @ torch.linalg.inv(Rbasis.T)) @ Rbasis.T
    return torch.exp(-dq.square().sum(dim=-1) / sigma**2).detach()


def run(
    *,
    specularity: float,
    N_theta: int,
    sigma: float,
    q0: torch.Tensor,
    v0: torch.Tensor,
    dt_save: float,
    t_max: float,
    r_c: float,
    mesh_file: str,
    save_frames: bool = False,
    process_grid_shape: Optional[Sequence[int]],
    order: int = 3,
) -> float:
    """Run DG (tri_set) advection on an external mesh; report MAE in density."""
    vF = v0.norm().item()
    init_angle = torch.atan2(v0[1], v0[0]).item()
    dt_save_ = 2 * t_max
    if save_frames:
        dt_save_ = dt_save
    transport = Transport(
        fermi_circle=dict(
            kF=1.0, vF=vF, N_theta=N_theta, theta0=init_angle,
            tau_p=np.inf, tau_ee=np.inf, r_c=r_c, specularity=specularity,
        ),
        tri_set=dict(mesh_file=mesh_file, contacts={}, order=order),
        time_evolution=dict(t_max=t_max, dt_save=dt_save_, n_collate=10),
        checkpoint_out="animation/advect_{:04d}.h5",
        process_grid_shape=process_grid_shape,
    )
    geometry = transport.geometry
    dg = geometry.dg

    Rnp = getattr(dg, "_lattice", None)
    if Rnp is not None and np.asarray(Rnp).shape == (2, 2):
        Rbasis = torch.from_numpy(np.asarray(Rnp, float)).to(rc.device)
    else:
        log.info("Lattice vectors set to bounding box: IGNORE reported rho_mae.")
        bbox_size = np.array([dg.x.max() - dg.x.min(), dg.y.max() - dg.y.min()])
        Rbasis = torch.diag(torch.from_numpy(bbox_size)).to(rc.device)

    q_nodes = torch.from_numpy(np.stack([dg.x, dg.y], axis=-1)).to(rc.device)
    if transport.material.comm.rank == 0:
        dens = torch.zeros_like(geometry.density)
        dens[:, :, 0] = gaussian_blob(q_nodes, q0, Rbasis, sigma).to(dens)
        geometry.density = dens          # stores conservative variable w = M u

    transport.run()

    q_final = q0 + v0 * transport.time_evolution.t
    rho0 = geometry.density[:, :, 0].detach().cpu().numpy()
    exact = gaussian_blob(q_nodes, q_final, Rbasis, sigma).detach().cpu().numpy()
    rho_err = dg.integrate(np.abs(rho0 - exact))
    rho_sum = dg.integrate(exact)
    rho_mae = float(rho_err / rho_sum)
    log.info(f"Done with {rho_mae = :.6f} at t[s]: {rc.clock():.2f}")
    return rho_mae


def _step_rk4(g, dt, nt, t0=0.0):
    for it in range(nt):
        r0 = g.rho; t = t0 + it * dt
        k1 = g.rho_dot(r0, t); k2 = g.rho_dot(r0 + (0.5 * dt) * k1, t + 0.5 * dt)
        k3 = g.rho_dot(r0 + (0.5 * dt) * k2, t + 0.5 * dt)
        k4 = g.rho_dot(r0 + dt * k3, t + dt)
        g.rho = r0 + (dt / 6.0) * (k1 + 2 * (k2 + k3) + k4)


def test_reflective_conservation(tmp_path):
    """Specular reflective walls conserve total mass to ~machine precision."""
    from .._transport import Transport
    rc.init()
    mesh = _make_rect_mesh(8.0, str(tmp_path / "rect.npz"))
    transport = Transport(
        fermi_circle=dict(kF=1.0, vF=1.5, N_theta=8, theta0=0.0, tau_p=np.inf,
                          tau_ee=np.inf, r_c=np.inf, specularity=1.0),
        tri_set=dict(mesh_file=mesh, contacts={}, order=3),
        time_evolution=dict(t_max=1.0, dt_save=2.0, n_collate=10),
    )
    g = transport.geometry; dg = g.dg
    q = np.stack([dg.x, dg.y], axis=-1); q0 = np.array([55.0, 30.0])
    blob = np.exp(-(((q - q0) ** 2).sum(-1)) / (2 * 6.0 ** 2))
    if transport.material.comm.rank == 0:
        dens = torch.zeros_like(g.density)
        dens[:, :, 0] = torch.as_tensor(blob).to(dens)
        g.density = dens
    mass = lambda: float(g._rho.sum()); m0 = mass()
    dt = 0.5 * g.dt_max
    _step_rk4(g, dt, int(45.0 / dt))
    assert abs(mass() - m0) / abs(m0) < 1e-9, "reflective walls not conserving mass"


def test_contact_steady_state(tmp_path):
    """Source/drain contacts (dmu=+/-0.1) drive a stable, bounded steady state."""
    from .._transport import Transport
    rc.init()
    mesh = _make_rect_mesh(8.0, str(tmp_path / "rect.npz"))
    transport = Transport(
        fermi_circle=dict(kF=1.0, vF=1.5, N_theta=12, theta0=0.0, tau_p=np.inf,
                          tau_ee=np.inf, r_c=np.inf, specularity=1.0),
        tri_set=dict(mesh_file=mesh,
                     contacts={"source": {"dmu": 0.1}, "drain": {"dmu": -0.1}},
                     order=3),
        time_evolution=dict(t_max=1.0, dt_save=2.0, n_collate=10),
    )
    g = transport.geometry
    if transport.material.comm.rank == 0:
        g.density = torch.zeros_like(g.density)
    dt = 0.5 * g.dt_max
    _step_rk4(g, dt, int(50.0 / dt))
    pot = g.density.mean(dim=2)
    assert torch.isfinite(pot).all(), "contact-driven solution diverged"
    assert float(pot.abs().max()) < 0.15, "interior potential exceeds contact range"


@pytest.mark.skip(reason="Curved isoparametric boundaries require arc projectors "
                         "in the external mesh format; not yet supported since "
                         "meshing moved out of qimpy.")
def test_curved_mass_conservation():
    ...


def main():
    log_config()
    rc.init()
    parser = argparse.ArgumentParser()
    parser.add_argument("--specularity", type=float, required=True)
    parser.add_argument("--Ntheta", type=int, required=True)
    parser.add_argument("--sigma", type=float, required=True)
    parser.add_argument("--q0", nargs=2, type=float, required=True)
    parser.add_argument("--v0", nargs=2, type=float, required=True)
    parser.add_argument("--dt_save", type=float, required=True)
    parser.add_argument("--r_c", type=float, default=np.inf)
    parser.add_argument("--t_max", type=float, required=True)
    parser.add_argument("--mesh", help="external mesh (.npz)", type=str, required=True)
    parser.add_argument("-p", "--process-grid", type=int, nargs=2, default=[-1, -1])
    args = parser.parse_args()
    run(
        N_theta=args.Ntheta, sigma=args.sigma, specularity=args.specularity,
        q0=torch.tensor(args.q0, device=rc.device),
        v0=torch.tensor(args.v0, device=rc.device),
        dt_save=args.dt_save, t_max=args.t_max, r_c=args.r_c,
        mesh_file=args.mesh, save_frames=True,
        process_grid_shape=args.process_grid,
    )


if __name__ == "__main__":
    main()


def test_spatial_mpi_matches_serial(tmp_path):
    """Spatial domain decomposition reproduces the serial DG result bit-for-bit
    on a contact-driven problem (halo emulated in-process; the real mpi4py
    transport moves the identical buffers)."""
    from qimpy.mpi import ProcessGrid
    from qimpy.transport.material import FermiCircle
    from ._dg_mesh import load_mesh
    from ._dg2d import DG2D
    from ._dg_mpi import (compute_partition, SpatialPartition,
                          DistributedAdvect, emulate_halo)
    rc.init()
    torch.set_default_dtype(torch.float64)
    mesh = load_mesh(_make_rect_mesh(8.0, str(tmp_path / "rect.npz")))
    pg = ProcessGrid(rc.comm, "rk", (1, 1))           # all channels local
    mat = FermiCircle(kF=1.0, vF=1.5, N_theta=8, theta0=0.0, tau_p=np.inf,
                      tau_ee=np.inf, r_c=np.inf, specularity=1.0, process_grid=pg)
    contacts = {"source": {"dmu": 0.1}, "drain": {"dmu": -0.1}}
    order, nsteps = 2, 16
    dt = 0.5 * float(DG2D(order, mesh.VX, mesh.VY, mesh.EToV).dt_scale) / 1.5

    def initial(adv, dg):
        x, y = np.asarray(dg.x), np.asarray(dg.y)
        u0 = np.zeros((dg.Np, dg.K, adv.Nk))
        u0[:, :, 0] = np.exp(-((x - 55) ** 2 + (y - 30) ** 2) / (2 * 8.0 ** 2))
        return adv.adv.apply_mass(torch.from_numpy(u0))

    def run(nparts):
        part = compute_partition(mesh, nparts)
        parts = [SpatialPartition(mesh, order, part, r) for r in range(nparts)]
        advs = [DistributedAdvect(p, mat, contacts) for p in parts]
        ws = [initial(advs[r], parts[r].dg) for r in range(nparts)]

        def rhs(stage):
            emulate_halo(parts, stage)
            return [advs[r].local_rhs(stage[r]) for r in range(nparts)]

        for _ in range(nsteps):
            k1 = rhs([w.clone() for w in ws])
            k2 = rhs([ws[r] + 0.5 * dt * k1[r] for r in range(nparts)])
            k3 = rhs([ws[r] + 0.5 * dt * k2[r] for r in range(nparts)])
            k4 = rhs([ws[r] + dt * k3[r] for r in range(nparts)])
            ws = [ws[r] + (dt / 6.0) * (k1[r] + 2 * (k2[r] + k3[r]) + k4[r])
                  for r in range(nparts)]
        K = len(mesh.EToV)
        full = np.zeros((parts[0].dg.Np, K, advs[0].Nk))
        for r in range(nparts):
            no = parts[r].n_owned
            full[:, parts[r].local2global_elem[:no], :] = \
                ws[r].detach().cpu().numpy()[:, :no, :]
        return full

    serial, par = run(1), run(4)
    assert np.abs(par - serial).max() < 1e-12, "spatial decomposition != serial"
